name: Deploy to EC2

on:
  push:
    branches:
      - 'frontend-service'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to EC2 instance
        run: ssh -o StrictHostKeyChecking=no -A ec2-user@3.121.112.56

      - name: Deploy application
        run: docker-compose up -d
