name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: azure/setup-k8s@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Deploy frontend service
      run: kubectl apply -f kubernetes/frontend-service.yaml

    - name: Deploy orders service
      run: kubectl apply -f kubernetes/orders-service.yaml

    - name: Deploy products service
      run: kubectl apply -f kubernetes/products-service.yaml
